services:
  yii2-app:
    build: .
    container_name: yii2-app
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    environment:
      - YII_DEBUG=1
      - YII_ENV=dev

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cook
      MYSQL_USER: zavristche
      MYSQL_PASSWORD: zavristche
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  # DEVELOPER
  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/vite.config.js:/app/vite.config.js:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
